apiVersion: apps/v1
kind: Deployment
metadata:
  name: rivertup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: srimanasa1/rivertup:latest
        ports:
          - containerPort: 3007
        env:
         - name: MONGODB_URI
           value: "mongodb://mongodb:27017/Survey"
      - name: docker
        image: mongo:latest
        ports:
           - containerPort: 27017